parameters:
  stripe_secret_key: "%env(STRIPE_SECRET_KEY)%"
  stripe_public_key: "%env(STRIPE_PUBLIC_KEY)%"

services:
  # Abonnements aux événements (event subscribers)
  App\EventSubscriber\TwigGlobalSubscriber:
    arguments:
      $categoryRepository: '@App\Repository\CategoryRepository'
      $twig: "@twig"
    tags: ["kernel.event_subscriber"]

  # Google OAuth User Provider
  App\Security\GoogleUserProvider:
    arguments:
      $em: "@doctrine.orm.entity_manager"

  # User Provider pour authentification classique
  App\Security\UserProvider:
    arguments:
      $entityManager: "@doctrine.orm.entity_manager"

  # Authenticator pour Google OAuth
  App\Security\GoogleAuthenticator:
    arguments:
      $client: "@knpu.oauth2.client.google"
      $router: "@router"

  App\Security\AccessDeniedHandler:
    arguments: ["@router"]
    tags: ["monolog.logger", "security.access_denied_handler"]

  App\EventSubscriber\RedirectBannedSubscriber:
    arguments:
      $security: "@security" # Injection du bon service
      $urlGenerator: "@router"
    tags:
      - { name: kernel.event_subscriber }

  # Autres services de votre application
  App\:
    resource: "../../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
