<?php

namespace ContainerDJJxE8y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkillRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\SkillRepository' shared autowired service.
     *
     * @return \App\Repository\SkillRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/SkillRepository.php';

        return $container->privates['App\\Repository\\SkillRepository'] = new \App\Repository\SkillRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
