nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:4200"] # Front Angular
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/api/": # Appliquer les règles uniquement pour les routes de l'API
      allow_origin: ["http://localhost:4200"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
