security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # User Providers: Load users from the database
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email # Field in User entity used for login

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      stateless: false # Enables session-based authentication

      # Enable form-based login
      form_login:
        login_path: login # Route for login form
        check_path: login # Route to process the login request

      # Logout settings
      logout:
        path: logout # Route for logging out

  # Access control: Define roles for specific paths
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
