version: "3.8"

services:
  ### Service PHP + Symfony ###
  app:
    build: .
    container_name: symfony_app
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - symfony_network

  ### Service Nginx ###
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

  ### Service MySQL ###
  database:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    networks:
      - symfony_network

  ### Service phpMyAdmin ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
