<?php

namespace ContainerF5v9LI4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Job' shared service.
     *
     * @return \App\Entity\Job
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Job.php';

        return $container->privates['App\\Entity\\Job'] = new \App\Entity\Job();
    }
}
