<?php

namespace ContainerF5v9LI4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceDetailControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..wKp6bH.App\Controller\ServiceDetailController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..wKp6bH.App\\Controller\\ServiceDetailController::detail()'] = ($container->privates['.service_locator..wKp6bH'] ?? $container->load('get_ServiceLocator__WKp6bHService'))->withContext('App\\Controller\\ServiceDetailController::detail()', $container);
    }
}
