<?php

namespace ContainerIEXj1DT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nU509g2.App\Controller\JobController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nU509g2.App\\Controller\\JobController::detail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'job' => ['privates', 'App\\Entity\\Job', 'getJobService', true],
        ], [
            'job' => 'App\\Entity\\Job',
        ]))->withContext('App\\Controller\\JobController::detail()', $container);
    }
}
