<?php

namespace ContainerHtptrqk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GE3yhlfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GE3yhlf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GE3yhlf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jobApplication' => ['privates', 'App\\Entity\\JobApplication', 'getJobApplicationService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'emailService' => ['privates', 'App\\Services\\EmailService', 'getEmailServiceService', true],
        ], [
            'jobApplication' => 'App\\Entity\\JobApplication',
            'entityManager' => '?',
            'emailService' => 'App\\Services\\EmailService',
        ]);
    }
}
