<?php

namespace ContainerHtptrqk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllerservicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZAUGEyP.App\Controller\CategoryController::services()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZAUGEyP.App\\Controller\\CategoryController::services()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', 'App\\Entity\\Category', 'getCategoryService', true],
        ], [
            'category' => 'App\\Entity\\Category',
        ]))->withContext('App\\Controller\\CategoryController::services()', $container);
    }
}
