<?php

namespace ContainerHtptrqk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControlleracceptApplicationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GE3yhlf.App\Controller\JobController::acceptApplication()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.GE3yhlf'] ?? $container->load('get_ServiceLocator_GE3yhlfService'));

        if (isset($container->privates['.service_locator.GE3yhlf.App\\Controller\\JobController::acceptApplication()'])) {
            return $container->privates['.service_locator.GE3yhlf.App\\Controller\\JobController::acceptApplication()'];
        }

        return $container->privates['.service_locator.GE3yhlf.App\\Controller\\JobController::acceptApplication()'] = $a->withContext('App\\Controller\\JobController::acceptApplication()', $container);
    }
}
