<?php

namespace ContainerHtptrqk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobApplicationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\JobApplication' shared service.
     *
     * @return \App\Entity\JobApplication
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/JobApplication.php';

        return $container->privates['App\\Entity\\JobApplication'] = new \App\Entity\JobApplication();
    }
}
