<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Service extends \App\Entity\Service implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'demoUrl' => [parent::class, 'demoUrl', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'reservedBy' => [parent::class, 'reservedBy', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'userService' => [parent::class, 'userService', null],
        'categories' => [parent::class, 'categories', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'demoUrl' => [parent::class, 'demoUrl', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'price' => [parent::class, 'price', null],
        'reservations' => [parent::class, 'reservations', null],
        'reservedBy' => [parent::class, 'reservedBy', null],
        'title' => [parent::class, 'title', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'userService' => [parent::class, 'userService', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
