<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIEXj1DT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIEXj1DT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIEXj1DT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIEXj1DT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIEXj1DT\App_KernelDevDebugContainer([
    'container.build_hash' => 'IEXj1DT',
    'container.build_id' => 'e342d4d2',
    'container.build_time' => 1738677539,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIEXj1DT');
