<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHtptrqk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHtptrqk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHtptrqk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHtptrqk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHtptrqk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Htptrqk',
    'container.build_id' => '7aa4ea0c',
    'container.build_time' => 1738754605,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHtptrqk');
