<?php

namespace ContainerTd6eoVb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7lCRvYA.App\Controller\JobController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.7lCRvYA'] ?? $container->load('get_ServiceLocator_7lCRvYAService'));

        if (isset($container->privates['.service_locator.7lCRvYA.App\\Controller\\JobController::create()'])) {
            return $container->privates['.service_locator.7lCRvYA.App\\Controller\\JobController::create()'];
        }

        return $container->privates['.service_locator.7lCRvYA.App\\Controller\\JobController::create()'] = $a->withContext('App\\Controller\\JobController::create()', $container);
    }
}
