<?php

namespace ContainerTd6eoVb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ProfileRepository' shared autowired service.
     *
     * @return \App\Repository\ProfileRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ProfileRepository.php';

        return $container->privates['App\\Repository\\ProfileRepository'] = new \App\Repository\ProfileRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
