<?php

namespace ContainerOQOy517;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerrejectApplicationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.trJhFxk.App\Controller\DashboardController::rejectApplication()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.trJhFxk.App\\Controller\\DashboardController::rejectApplication()'] = ($container->privates['.service_locator.trJhFxk'] ?? $container->load('get_ServiceLocator_TrJhFxkService'))->withContext('App\\Controller\\DashboardController::rejectApplication()', $container);
    }
}
