<?php

namespace ContainerOQOy517;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFreelancerControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MtXMf3E.App\Controller\FreelancerController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MtXMf3E.App\\Controller\\FreelancerController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'freelancerRepository' => ['privates', 'App\\Repository\\FreelancerRepository', 'getFreelancerRepositoryService', true],
        ], [
            'freelancerRepository' => 'App\\Repository\\FreelancerRepository',
        ]))->withContext('App\\Controller\\FreelancerController::index()', $container);
    }
}
