<?php

namespace ContainerOQOy517;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Reservation.php';

        return $container->privates['App\\Entity\\Reservation'] = new \App\Entity\Reservation();
    }
}
