<?php

namespace ContainerOQOy517;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendTestEmailCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SendTestEmailCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SendTestEmailCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:send-test-email', [], 'Envoie un email de test à une adresse spécifiée.', false, #[\Closure(name: 'App\\Command\\SendTestEmailCommand')] fn (): \App\Command\SendTestEmailCommand => ($container->privates['App\\Command\\SendTestEmailCommand'] ?? $container->load('getSendTestEmailCommandService')));
    }
}
