<?php

namespace Container1la6aLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0jUX5FG.App\Controller\ClientController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0jUX5FG.App\\Controller\\ClientController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', 'App\\Entity\\Client', 'getClientService', true],
        ], [
            'client' => 'App\\Entity\\Client',
        ]))->withContext('App\\Controller\\ClientController::show()', $container);
    }
}
