<?php

namespace Container1la6aLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ReservationRepository' shared autowired service.
     *
     * @return \App\Repository\ReservationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ReservationRepository.php';

        return $container->privates['App\\Repository\\ReservationRepository'] = new \App\Repository\ReservationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
