<?php

namespace Container1la6aLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Service' shared service.
     *
     * @return \App\Entity\Service
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Service.php';

        return $container->privates['App\\Entity\\Service'] = new \App\Entity\Service();
    }
}
